// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"github.com/maczh/utils"
	"github.com/swaggo/swag"
	"mgate/service"
)

var apiJson = service.GetApiDocsJson()

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     apiJson.Version,
	Host:        apiJson.Host,
	BasePath:    apiJson.BasePath,
	Schemes:     []string{},
	Title:       apiJson.Title,
	Description: apiJson.Description,
}

type s struct{}

func (s *s) ReadDoc() string {
	return utils.ToJSON(service.GetApiDocsJson())
}

func Init() {
	swag.Register("swagger", &s{})
}
